config/routes.rb
Rails.application.routes.draw do
  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'search'=> 'searches#search'
    resources :orders, only:[:show, :update] do
      resources :order_details, only:[:update]
    end
    get '' => 'orders#index'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/order_confirm'
    get 'orders/complete'
    delete 'cart_items/all_destroy'
    get 'customers/quit_confirm'
    patch 'customers/quit'
    get 'search'=> 'searches#search'
    resources :orders, only:[:new, :show, :index, :create]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resource :customers, only:[:show, :edit, :update]
    resources :shipping_addresses, only:[:index, :edit, :create, :update, :destroy]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :orders
  has_many :shipping_addresses

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/ }
  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z/ }

  def address_display
    "〒" + postal_code + " " + address
  end

  def name_display
    last_name + first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "会員情報を変更しました。"
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:index, :show]
  def index
    @cart_items = current_customer.cart_items.all
  end

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    if current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
      cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.save
      redirect_to cart_items_path
    elsif @cart_item.save
      flash.now[:notice] = "カートに商品を追加しました。"
      @cart_items = current_customer.cart_items.all
      render 'index'
    else
      render 'index'
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_items = current_customer.cart_items.all
    if @cart_item.update(cart_item_params)
      flash.now[:notice] = "商品の数量を変更しました。"
    end
  end

  def destroy
    @cart_items = current_customer.cart_items.all
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
  end

  def all_destroy
    @cart_items = CartItem.all
    @cart_items.destroy_all
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path, notice: "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  def quit_confirm
    @customer = current_customer
  end

  def quit
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会しました。"
  end


  private

  def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.limit(4).order("created_at DESC")
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:top, :about, :index, :show]
  def index
    @items = Item.page(params[:page])
    @genres = Genre.all
    if params[:id]
      @genre = Genre.find(params[:id])
      @items = @genre.items.page(params[:page])
    else
      @items = Item.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])

    @cart_item = CartItem
    @genres = Genre.all
  end


  private

  def item_params
   params.require(:items).permit(:genre_id, :name, :introduction, :price, :image)
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_cart_item, only: [:new, :order_confirm]

  def new
    @order = Order.new
  end

  def order_confirm
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @shipping_cost = 800
    @total_price = 0
    if params[:order][:address_number] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_number] == "2"
      @order.postal_code = ShippingAddress.find(params[:order][:shipping_address_id]).postal_code
      @order.address = ShippingAddress.find(params[:order][:shipping_address_id]).address
      @order.name = ShippingAddress.find(params[:order][:shipping_address_id]).name
    elsif params[:order][:address_number] == "3"
      @order.customer_id = current_customer.id
      unless @order.valid?
        render :new
      end
    else
      render :new
    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items = current_customer.cart_items.all
      cart_items.each do |cart_item|
        @order_detail = OrderDetail.new
        @order_detail.item_id = cart_item.item_id
        @order_detail.order_id = @order.id
        @order_detail.price = cart_item.item.add_tax_price
        @order_detail.amount = cart_item.amount
        @order_detail.making_status = OrderDetail.making_statuses.key(0)
        @order_detail.save
      end
      cart_items.destroy_all
      redirect_to orders_complete_path
    else
      render :new
    end
  end

  def complete
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.where(customer_id: current_customer.id)
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :shipping_cost, :total_payment, :status)
  end

  def ensure_cart_item
    cart_items = current_customer.cart_items.all
    unless cart_items.present?
      redirect_to items_path
    end
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/searches_controller.rb
class Customer::SearchesController < ApplicationController
  def search
    @q = params[:q][:name_cont]
  end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :customer_state, only: [:create]

  protected

  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted
      redirect_to new_customer_registration_path, notice: "退会済みのユーザーです。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController
  before_action :authenticate_customer!
  def create
    @shipping_address = ShippingAddress.new(shipping_address_params)
    @shipping_address.customer_id = current_customer.id
    if @shipping_address.save
       @shipping_address = ShippingAddress.new(shipping_address_params)
       @shipping_addresses = current_customer.shipping_addresses
       flash.now[:notice] = "配送先を登録しました。"
    else
       @shipping_addresses = current_customer.shipping_addresses
    end
  end

  def index
    @shipping_address = ShippingAddress.new
    @shipping_addresses = current_customer.shipping_addresses
  end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    if @shipping_address.update(shipping_address_params)
      redirect_to shipping_addresses_path, notice: "配送先を変更しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @shipping_addresses = current_customer.shipping_addresses
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    flash.now[:notice] = "配送先を削除しました。"
  end


  private

  def shipping_address_params
    params.require(:shipping_address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/views/customer/customers/edit.html.erb
<div class="container col-5 mx-auto mt-5">
  <h2 class="mb-5">会員情報編集</h2>
  <%= render 'layouts/errors', obj: @customer %>
  <div class="row">
    <div>
     <%= form_with model: @customer, url: customers_path, local:true do |f| %>
      <table>
          <tr>
            <td class="pt-3">氏名</td>
            <td align="right" class="pt-3"></td>
            <td class="pt-3 pl-4"><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: 'form-control' %></td>
            <td class="pl-3 pt-3"></td>
            <td class="pt-3"><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: 'form-control' %></td>
          </tr>
          <tr>
            <td class="pt-3">フリガナ</td>
            <td align="right" class="pt-3"></td>
            <td class="pt-3 pl-4"><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class: 'form-control' %></td>
            <td class="pl-3 pt-3"></td>
            <td class="pt-3"><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class: 'form-control' %></td>
          </tr>
          <tr>
            <td colspan="2" class="pt-4"><%= f.label :郵便番号 %></td>
            <td class="pt-3 pl-4"><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class: 'form-control' %></td>
          </tr>
          <tr>
            <td colspan="2" class="pt-4"><%= f.label :住所 %></td>
            <td colspan="3" class="pt-3 pl-4"><%= f.text_field :address, autofocus: true, autocomplete: "address", class: 'form-control' %></td>
          </tr>
          <tr>
            <td colspan="2" class="pt-4"><%= f.label :電話番号 %></td>
            <td class="pt-3 pl-4"><%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class: 'form-control' %></td>
          </tr>
          <tr>
            <td colspan="2" class="pt-4"><%= f.label :メールアドレス %></td>
            <td class="pt-3 pl-4"><%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %></td>
          </tr>
          <tr>
            <td align="center" colspan="3" class="pt-4"><%= f.submit "編集内容を保存", class: 'btn w-30',style: "background-color: #816F5B; color: #fff;" %></td>
            <td align="center" colspan="3" class="pt-4"><%= link_to '退会する', customers_quit_confirm_path, class: 'btn btn-danger w-30' %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/customers/quit_confirm.html.erb
<div class='container py-5'>
  <div class='row'>
    <h4 class="px-3 mx-auto"><strong>本当に退会しますか？</strong></h4>
  </div>
  <br>
  <div class='row'>
    <h4 class="px-3 mx-auto">退会すると、会員登録情報や</h4>
  </div>
  <div class='row'>
    <h4 class="px-3 mx-auto">これまでの購入履歴が閲覧できなくなります。</h4>
  </div>
  <div class='row'>
    <h4 class="px-3 mx-auto">退会する場合は、「退会する」をクリックしてください。</h4>
  </div><br>
  <div class='row'>
    <h4 class="px-3 mx-auto">
      <%= link_to '退会しない', customers_path, class: "btn btn-secondary" %>
      <%= link_to '退会する', customers_quit_path, method: :patch, class: "btn btn-danger" %>
    </h4>
  </div>
</div>

app/views/customer/customers/show.html.erb
<div class="container-xxl mt-5 mx-5">

 <h2 class="ml-5">マイページ</h2>

  <div class="customer-information mt-5">
    <div class="row" style="margin-left: 0; margin-right: 0;">
      <h4 class="d-flex align-items-center justify-content-center" style="margin-bottom: 0;"><strong>登録情報</strong></h4>
      <%= link_to "編集する", edit_customers_path, class: "btn ml-5",style: "background-color: #816F5B; color: #fff;" %>
    </div>
    <table class="col-7 table table-bordered mt-3 mb-5">
      <tr>
        <td class="col-3 table-active border border-dark">氏名</td>
        <td class="border border-dark"><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td class="col-3 table-active border border-dark">カナ</td>
        <td class="border border-dark"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td class="col-3 table-active border border-dark">郵便番号</td>
        <td class="border border-dark"><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td class="col-3 table-active border border-dark">住所</td>
        <td class="border border-dark"><%= @customer.address %></td>
      </tr>
      <tr>
        <td class="col-3 table-active border border-dark">電話番号</td>
        <td class="border border-dark"><%= @customer.phone_number %></td>
      </tr>
      <tr>
        <td class="col-3 table-active border border-dark">メールアドレス</td>
        <td class="border border-dark"><%= @customer.email %></td>
      </tr>
    </table>

    <div class="row col-3" style="margin-left: 0; margin-right: 0; padding-left: 0;">
      <h4 class="col-6 d-flex align-items-center justify-content-left" style="margin-bottom: 0; padding-left: 0;"><strong>配送先</strong></h4>
      <%= link_to "一覧を見る", shipping_addresses_path, class: "col-6 btn btn-secondary" %>
      <div class="w-100 mt-4"></div>
      <h4 class="col-6 d-flex align-items-center justify-content-left" style="margin-bottom: 0; padding-left: 0;"><strong>注文履歴</strong></h4>
      <%= link_to "一覧を見る", orders_path, class: "col-6 btn btn-secondary" %>
    </div>

  </div>
</div>