config/routes.rb
Rails.application.routes.draw do
  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'search'=> 'searches#search'
    resources :orders, only:[:show, :update] do
      resources :order_details, only:[:update]
    end
    get '' => 'orders#index'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/order_confirm'
    get 'orders/complete'
    delete 'cart_items/all_destroy'
    get 'customers/quit_confirm'
    patch 'customers/quit'
    get 'search'=> 'searches#search'
    resources :orders, only:[:new, :show, :index, :create]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resource :customers, only:[:show, :edit, :update]
    resources :shipping_addresses, only:[:index, :edit, :create, :update, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, production: 2, preparing_delivery: 3, delivered: 4 }

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :name, presence: true

  def total_amount
    number = 0
    self.order_details.each do |order_detail|
      number += order_detail.amount
    end
    number
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id), notice: "会員情報を変更しました。"
    else
      render "edit"
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_deleted)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:customer_id] != nil && params[:status] != nil
      @orders = Order.where(customer_id: params[:customer_id], status: params[:status]).order(created_at: "DESC").page(params[:page])
      @heading = "#{Customer.find(params[:customer_id]).name_display}さんの注文履歴「#{Order.statuses_i18n[params[:status]]}」（全#{ Order.where(customer_id: params[:customer_id], status: params[:status]).count}件）"
      @customer_id = params[:customer_id]
    elsif params[:customer_id] != nil
      @orders = Order.where(customer_id: params[:customer_id]).order(created_at: "DESC").page(params[:page])
      @heading =  "#{Customer.find(params[:customer_id]).name_display}さんの注文履歴（全#{Order.where(customer_id: params[:customer_id]).count}件）"
      @customer_id = params[:customer_id]
    elsif params[:status] != nil
      @orders = Order.where(status: params[:status]).order(created_at: "DESC").page(params[:page])
      @heading = "注文履歴詳細「#{Order.statuses_i18n[params[:status]]}」（全#{Order.where(status: params[:status]).count}件）"
      @customer_id = nil
      @count_status = count_status
    else
      @orders = Order.all.order(created_at: "DESC").page(params[:page])
      @heading = "注文履歴一覧（全#{Order.all.count}件）"
      @customer_id = nil
      @count_status = count_status
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    if params[:order][:id] == nil
      @order = Order.find(params[:id])
    else
      @order = Order.find(params[:order][:id])
    end
    @order.update(order_params)
    if params[:order][:status] == Order.statuses.key(1)
      @order.order_details.each do |order_detail|
        order_detail.making_status = OrderDetail.making_statuses.key(1)
        order_detail.save
      end
    end
    # 非同期通信(jsファイルへの受け渡し:@order)
    # redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def count_status
    status_name_0 = Order.statuses_i18n[Order.statuses.key(0)]
    status_num_0 = Order.where(status: Order.statuses.key(0)).count
    status_name_1 = Order.statuses_i18n[Order.statuses.key(1)]
    status_num_1 = Order.where(status: Order.statuses.key(1)).count
    status_name_2 = Order.statuses_i18n[Order.statuses.key(2)]
    status_num_2 = Order.where(status: Order.statuses.key(2)).count
    status_name_3 = Order.statuses_i18n[Order.statuses.key(3)]
    status_num_3 = Order.where(status: Order.statuses.key(3)).count
    status_name_4 = Order.statuses_i18n[Order.statuses.key(4)]
    status_num_4 = Order.where(status: Order.statuses.key(4)).count
    "「#{status_name_0}」:#{status_num_0}件, 「#{status_name_1}」:#{status_num_1}件, 「#{status_name_2}」:#{status_num_2}件, 「#{status_name_3}」:#{status_num_3}件, 「#{status_name_4}」:#{status_num_4}件"
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:index, :show]
  def index
    @cart_items = current_customer.cart_items.all
  end

  def create
    @cart_item = current_customer.cart_items.new(cart_item_params)
    if current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
      cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.save
      redirect_to cart_items_path
    elsif @cart_item.save
      flash.now[:notice] = "カートに商品を追加しました。"
      @cart_items = current_customer.cart_items.all
      render 'index'
    else
      render 'index'
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_items = current_customer.cart_items.all
    if @cart_item.update(cart_item_params)
      flash.now[:notice] = "商品の数量を変更しました。"
    end
  end

  def destroy
    @cart_items = current_customer.cart_items.all
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
  end

  def all_destroy
    @cart_items = CartItem.all
    @cart_items.destroy_all
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customers_path, notice: "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  def quit_confirm
    @customer = current_customer
  end

  def quit
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会しました。"
  end


  private

  def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email)
  end

end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    @items = Item.limit(4).order("created_at DESC")
    @genres = Genre.all
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:top, :about, :index, :show]
  def index
    @items = Item.page(params[:page])
    @genres = Genre.all
    if params[:id]
      @genre = Genre.find(params[:id])
      @items = @genre.items.page(params[:page])
    else
      @items = Item.page(params[:page])
    end
  end

  def show
    @item = Item.find(params[:id])

    @cart_item = CartItem
    @genres = Genre.all
  end


  private

  def item_params
   params.require(:items).permit(:genre_id, :name, :introduction, :price, :image)
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_cart_item, only: [:new, :order_confirm]

  def new
    @order = Order.new
  end

  def order_confirm
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @shipping_cost = 800
    @total_price = 0
    if params[:order][:address_number] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_number] == "2"
      @order.postal_code = ShippingAddress.find(params[:order][:shipping_address_id]).postal_code
      @order.address = ShippingAddress.find(params[:order][:shipping_address_id]).address
      @order.name = ShippingAddress.find(params[:order][:shipping_address_id]).name
    elsif params[:order][:address_number] == "3"
      @order.customer_id = current_customer.id
      unless @order.valid?
        render :new
      end
    else
      render :new
    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items = current_customer.cart_items.all
      cart_items.each do |cart_item|
        @order_detail = OrderDetail.new
        @order_detail.item_id = cart_item.item_id
        @order_detail.order_id = @order.id
        @order_detail.price = cart_item.item.add_tax_price
        @order_detail.amount = cart_item.amount
        @order_detail.making_status = OrderDetail.making_statuses.key(0)
        @order_detail.save
      end
      cart_items.destroy_all
      redirect_to orders_complete_path
    else
      render :new
    end
  end

  def complete
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.where(customer_id: current_customer.id)
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :shipping_cost, :total_payment, :status)
  end

  def ensure_cart_item
    cart_items = current_customer.cart_items.all
    unless cart_items.present?
      redirect_to items_path
    end
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/searches_controller.rb
class Customer::SearchesController < ApplicationController
  def search
    @q = params[:q][:name_cont]
  end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :customer_state, only: [:create]

  protected

  def customer_state
    @customer = Customer.find_by(email: params[:customer][:email])
    return if !@customer
    if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted
      redirect_to new_customer_registration_path, notice: "退会済みのユーザーです。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customer/shipping_addresses_controller.rb
class Customer::ShippingAddressesController < ApplicationController
  before_action :authenticate_customer!
  def create
    @shipping_address = ShippingAddress.new(shipping_address_params)
    @shipping_address.customer_id = current_customer.id
    if @shipping_address.save
       @shipping_address = ShippingAddress.new(shipping_address_params)
       @shipping_addresses = current_customer.shipping_addresses
       flash.now[:notice] = "配送先を登録しました。"
    else
       @shipping_addresses = current_customer.shipping_addresses
    end
  end

  def index
    @shipping_address = ShippingAddress.new
    @shipping_addresses = current_customer.shipping_addresses
  end

  def edit
    @shipping_address = ShippingAddress.find(params[:id])
  end

  def update
    @shipping_address = ShippingAddress.find(params[:id])
    if @shipping_address.update(shipping_address_params)
      redirect_to shipping_addresses_path, notice: "配送先を変更しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @shipping_addresses = current_customer.shipping_addresses
    @shipping_address = ShippingAddress.find(params[:id])
    @shipping_address.destroy
    flash.now[:notice] = "配送先を削除しました。"
  end


  private

  def shipping_address_params
    params.require(:shipping_address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
end

app/views/customer/orders/complete.html.erb
<div class="container">
  <h2 class="text-center mt-5 mb-5">ご注文ありがとうございました！</h2>
  <div class="d-flex justify-content-center">
    <img src="/assets/thank_you.jpg" alt="">
  </div>
</div>

app/views/customer/orders/index.html.erb
<div class="container">
  <h2 class="mt-5 mb-5 ml-5 ">注文履歴一覧</h2>
  <table class="table table-bordered">
    <tr width="100%" bgcolor="#816F5B" class="text-light">
      <th width="10%">注文日</th>
      <th width="40%">配送先</th>
      <th width="15%">注文商品</th>
      <th width="10%">支払金額</th>
      <th width="10%">ステータス</th>
      <th width="15%">注文詳細</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td class="display-table-cell align-middle"><%= order.created_at.strftime("%Y/%m/%d") %></td>
        <td>
          <%= order.postal_code %><br>
          <%= order.address %><br>
          <%= order.name %>
        </td>
        <td>
          <% order.order_details.each do |order_detail| %>
            <%= order_detail.item.name %><br>
          <% end %>
        </td>
        <td class="display-table-cell align-middle">￥<%= order.total_payment.to_s(:delimited) %></td>
        <td class="display-table-cell align-middle"><%= Order.statuses_i18n[order.status] %></td>
        <td class="display-table-cell align-middle"><%= link_to "表示する", order_path(order), class: "btn btn-secondary" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/customer/orders/new.html.erb
<div class="container">
  <h2 class="mt-5 mb-5 ml-5">注文情報入力</h2>
  <%= render "layouts/errors", obj: @order %>
  <p><strong>支払い方法</strong></p>
  <%= form_with model: @order, url: orders_order_confirm_path, method: :post, local: true do |f| %>
    <div class="ml-3">
      <%= f.radio_button :payment_method, Order.payment_methods.key(0), {:checked => true} %>
      <%= f.label :payment_method, Order.payment_methods_i18n[:credit_card] %><br>
    </div>
    <div class="ml-3 mb-3">
      <%= f.radio_button :payment_method, Order.payment_methods.key(1) %>
      <%= f.label :payment_method, Order.payment_methods_i18n[:transfer] %>
    </div>
    <p><strong>お届け先</strong></p>
    <div class="ml-3 mb-3">
      <%= f.radio_button :address_number,"1" %>
      <%= f.label :address_number_1, "ご自身の住所" %><br>
      <div class="ml-3">
        <%= current_customer.address_display %><br>
        <%= current_customer.name_display %><br>
      </div>
    </div>
    <% if current_customer.shipping_addresses.exists? %>
      <div class="ml-3 mb-3">
        <%= f.radio_button :address_number, "2" %>
        <%= f.label :address_number_2, "登録住所から選択" %><br>
        <div class="ml-3">
          <%= f.select :shipping_address_id, options_from_collection_for_select(current_customer.shipping_addresses.all, :id, :shipping_address_display), {}, class: 'form-control'  %><br>
        </div>
      </div>
    <% end %>
    <div class="ml-3 mb-3">
      <%= f.radio_button :address_number, "3" %>
      <%= f.label :address_number_3, "新しいお届け先" %><br>
      <div class="ml-3">
        <table width="100%">
          <tr>
            <td width="20%"><%= f.label "郵便番号(ハイフンなし)" %></td>
            <td width="40%"><%= f.text_field :postal_code , placeholder: "0000000", class: 'form-control' %></td>
            <td width="40%"></td>
          </tr>
          <tr>
            <td><%= f.label "住所" %></td>
            <td colspan="2"><%= f.text_field :address, placeholder: "東京都渋谷区代々木神園町0-0", class: 'form-control' %></td>
          </tr>
          <tr>
            <td><%= f.label "宛先" %></td>
            <td><%= f.text_field :name, placeholder: "令和道子", class: 'form-control' %></td>
            <td></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="d-flex justify-content-center ">
      <%= f.submit "確認画面に進む", class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/customer/orders/order_confirm.html.erb
<div class="container">
  <h2 class="mt-5 mb-5 ml-5">注文情報確認</h2>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <table class="table table-bordered">
          <tr bgcolor="#816F5B" class="text-light">
            <th>商品情報</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td><%= cart_item.item.name %></td>
              <td>￥<%= cart_item.item.add_tax_price.to_s(:delimited) %></td>
              <td><%= cart_item.amount.to_s(:delimited) %></td>
              <td>￥<%= cart_item.subtotal.to_s(:delimited) %></td>
              <% @total_price += cart_item.subtotal %>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="col-md-4">
        <table class="table table-bordered">
          <tr>
            <td bgcolor="#816F5B" class="text-light">送料</td>
            <td>￥<%= @shipping_cost.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td bgcolor="#816F5B" class="text-light">商品合計</td>
            <td>￥<%= @total_price.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td bgcolor="#816F5B" class="text-light">請求金額</td>
            <td>￥<%= (@shipping_cost + @total_price).to_s(:delimited) %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <table width="100%">
    <tr>
      <td width="10%"><strong>支払い方法</strong></td>
      <td width="90%"><%= Order.payment_methods_i18n[@order.payment_method] %></td>
    </tr>
    <tr>
      <td><strong>お届け先</strong></td>
      <td><%= @order.postal_code + @order.address %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= @order.name %></td>
    </tr>
  </table>

  <%= form_with model: @order, url: orders_path, method: :post, local: true do |f| %>
    <%= f.hidden_field :postal_code %>
    <%= f.hidden_field :address %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :shipping_cost, value: @shipping_cost %>
    <%= f.hidden_field :total_payment, value: @shipping_cost + @total_price %>
    <%= f.hidden_field :payment_method %>
    <%= f.hidden_field :status, value: Order.statuses.key(0) %>
    <div class="d-flex justify-content-center ">
      <%= f.submit "注文を確定する", class: "btn",style: "background-color: #816F5B; color: #fff;" %>
    </div>
  <% end %>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
  <h2 class="mt-5 mb-5 ml-5">注文履歴詳細</h2>
  <div class="row">
    <div class="col-md-8 pl-0">
      <p><strong>注文情報</strong></p>
      <table class="table table-bordered">
        <tr width="100%">
          <td width="20%" bgcolor="#816F5B" class="text-light">注文日</td>
          <td width="80%"><%= @order.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <td bgcolor="#816F5B" class="text-light">発送先</td>
          <td>
            <%= @order.postal_code%><br>
            <%= @order.address %><br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <td bgcolor="#816F5B" class="text-light">支払方法</td>
          <td><%= Order.payment_methods_i18n[@order.payment_method] %></td>
        </tr>
        <tr>
          <td bgcolor="#816F5B" class="text-light">ステータス</td>
          <td><%= Order.statuses_i18n[@order.status] %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-4 pr-0">
      <p><strong>請求情報</strong></p>
      <table class="table table-bordered">
        <tr width="100%">
          <td width="60%" bgcolor="#816F5B" class="text-light">商品合計</td>
          <td width="40%">￥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr>
          <td bgcolor="#816F5B" class="text-light">配送料</td>
          <td>￥<%= @order.shipping_cost.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td bgcolor="#816F5B" class="text-light"><strong>ご請求額</strong></td>
          <td>￥<%= @order.total_payment.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <p><strong>注文内容</strong></p>
    <table class="table table-bordered">
      <tr width="100%" bgcolor="#816F5B" class="text-light">
        <th width="70%">商品</th>
        <th width="10%">単価(税込)</th>
        <th width="10%">個数</th>
        <th width="10%">小計</th>
      </tr>
      <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td>￥<%= order_detail.price.to_s(:delimited) %></td>
          <td><%= order_detail.amount.to_s(:delimited) %></td>
          <td>￥<%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>