config/routes.rb
Rails.application.routes.draw do
  devise_for :customer, skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'search'=> 'searches#search'
    resources :orders, only:[:show, :update] do
      resources :order_details, only:[:update]
    end
    get '' => 'orders#index'
    resources :genres, only:[:index, :edit, :create, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :new, :show, :edit, :create, :update]
  end

  scope module: :customer do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    post 'orders/order_confirm'
    get 'orders/complete'
    delete 'cart_items/all_destroy'
    get 'customers/quit_confirm'
    patch 'customers/quit'
    get 'search'=> 'searches#search'
    resources :orders, only:[:new, :show, :index, :create]
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resource :customers, only:[:show, :edit, :update]
    resources :shipping_addresses, only:[:index, :edit, :create, :update, :destroy]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, production: 2, preparing_delivery: 3, delivered: 4 }

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :name, presence: true

  def total_amount
    number = 0
    self.order_details.each do |order_detail|
      number += order_detail.amount
    end
    number
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:customer_id] != nil && params[:status] != nil
      @orders = Order.where(customer_id: params[:customer_id], status: params[:status]).order(created_at: "DESC").page(params[:page])
      @heading = "#{Customer.find(params[:customer_id]).name_display}さんの注文履歴「#{Order.statuses_i18n[params[:status]]}」（全#{ Order.where(customer_id: params[:customer_id], status: params[:status]).count}件）"
      @customer_id = params[:customer_id]
    elsif params[:customer_id] != nil
      @orders = Order.where(customer_id: params[:customer_id]).order(created_at: "DESC").page(params[:page])
      @heading =  "#{Customer.find(params[:customer_id]).name_display}さんの注文履歴（全#{Order.where(customer_id: params[:customer_id]).count}件）"
      @customer_id = params[:customer_id]
    elsif params[:status] != nil
      @orders = Order.where(status: params[:status]).order(created_at: "DESC").page(params[:page])
      @heading = "注文履歴詳細「#{Order.statuses_i18n[params[:status]]}」（全#{Order.where(status: params[:status]).count}件）"
      @customer_id = nil
      @count_status = count_status
    else
      @orders = Order.all.order(created_at: "DESC").page(params[:page])
      @heading = "注文履歴一覧（全#{Order.all.count}件）"
      @customer_id = nil
      @count_status = count_status
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    if params[:order][:id] == nil
      @order = Order.find(params[:id])
    else
      @order = Order.find(params[:order][:id])
    end
    @order.update(order_params)
    if params[:order][:status] == Order.statuses.key(1)
      @order.order_details.each do |order_detail|
        order_detail.making_status = OrderDetail.making_statuses.key(1)
        order_detail.save
      end
    end
    # 非同期通信(jsファイルへの受け渡し:@order)
    # redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def count_status
    status_name_0 = Order.statuses_i18n[Order.statuses.key(0)]
    status_num_0 = Order.where(status: Order.statuses.key(0)).count
    status_name_1 = Order.statuses_i18n[Order.statuses.key(1)]
    status_num_1 = Order.where(status: Order.statuses.key(1)).count
    status_name_2 = Order.statuses_i18n[Order.statuses.key(2)]
    status_num_2 = Order.where(status: Order.statuses.key(2)).count
    status_name_3 = Order.statuses_i18n[Order.statuses.key(3)]
    status_num_3 = Order.where(status: Order.statuses.key(3)).count
    status_name_4 = Order.statuses_i18n[Order.statuses.key(4)]
    status_num_4 = Order.where(status: Order.statuses.key(4)).count
    "「#{status_name_0}」:#{status_num_0}件, 「#{status_name_1}」:#{status_num_1}件, 「#{status_name_2}」:#{status_num_2}件, 「#{status_name_3}」:#{status_num_3}件, 「#{status_name_4}」:#{status_num_4}件"
  end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_cart_item, only: [:new, :order_confirm]

  def new
    @order = Order.new
  end

  def order_confirm
    @order = Order.new(order_params)
    @cart_items = current_customer.cart_items.all
    @shipping_cost = 800
    @total_price = 0
    if params[:order][:address_number] == "1"
      @order.postal_code = current_customer.postal_code
      @order.address = current_customer.address
      @order.name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_number] == "2"
      @order.postal_code = ShippingAddress.find(params[:order][:shipping_address_id]).postal_code
      @order.address = ShippingAddress.find(params[:order][:shipping_address_id]).address
      @order.name = ShippingAddress.find(params[:order][:shipping_address_id]).name
    elsif params[:order][:address_number] == "3"
      @order.customer_id = current_customer.id
      unless @order.valid?
        render :new
      end
    else
      render :new
    end
  end

  def create
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items = current_customer.cart_items.all
      cart_items.each do |cart_item|
        @order_detail = OrderDetail.new
        @order_detail.item_id = cart_item.item_id
        @order_detail.order_id = @order.id
        @order_detail.price = cart_item.item.add_tax_price
        @order_detail.amount = cart_item.amount
        @order_detail.making_status = OrderDetail.making_statuses.key(0)
        @order_detail.save
      end
      cart_items.destroy_all
      redirect_to orders_complete_path
    else
      render :new
    end
  end

  def complete
  end

  def show
    @order = Order.find(params[:id])
  end

  def index
    @orders = Order.where(customer_id: current_customer.id)
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :shipping_cost, :total_payment, :status)
  end

  def ensure_cart_item
    cart_items = current_customer.cart_items.all
    unless cart_items.present?
      redirect_to items_path
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/_order_detail.html.erb
<table class="table">
  <tr width="100%" bgcolor="#816F5B" class="text-light">
    <th width="30%">商品名</th>
    <th width="20%">単価(税込)</th>
    <th width="10%">数量</th>
    <th width="10%">小計</th>
    <th width="30%">制作ステータス</th>
  </tr>
  <% order.order_details.each do |order_detail| %>
    <tr>
      <td><%= order_detail.item.name %></td>
      <td>￥<%= order_detail.price.to_s(:delimited) %></td>
      <td><%= order_detail.amount.to_s(:delimited) %></td>
      <td>￥<%= (order_detail.price * order_detail.amount).to_s(:delimited) %></td>
      <td>
        <div class="text-danger">
          <%= OrderDetail.making_statuses_i18n[order_detail.making_status] %>
        </div>
        <%= form_with model: order_detail, url: admin_order_order_detail_path(order_detail.order, order_detail), method: :patch, local: false do |f| %>
          <%= f.select :making_status, OrderDetail.making_statuses.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
          <%= f.submit "更新", class: "btn btn-sm" ,style: "background-color: #816F5B; color: #fff;" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/orders/_order_status.html.erb
<%= Order.statuses_i18n[order.status] %>
<%= form_with model: order, url: admin_order_path, method: :patch, local: false do |f| %>
  <%= f.select :status, Order.statuses.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
  <%= f.hidden_field :id, value: order.id %>
  <%= f.submit "更新", class: "btn btn-sm",style: "background-color: #816F5B; color: #fff;" %>
<% end %>

app/views/admin/orders/index.html.erb
<div class="container">
  <h2 class="mt-5 ml-5"><%= @heading %></h2>
  <% if  @customer_id == nil %>
    <p class="alert alert-secondary"><%= @count_status %></p>
  <% end %>
  <table class="table table-bordered">
    <tr width="100%" bgcolor="#816F5B" class="text-light">
      <th width="30%">購入日時</th>
      <% if @customer_id == nil %>
        <th width="20%">購入者</th>
      <% end %>
      <th width="20%">注文個数</th>
      <th width="30%">注文ステータス
        <%= form_with url: admin_path, method: :get, local: true do |f| %>
          <div class="form-inline">
            <%= f.select :status, Order.statuses.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]}, {}, class: 'form-control' %>
            <% if @customer_id != nil %>
              <%= f.hidden_field :customer_id, value: @customer_id %>
            <% end %>
            <%= f.button :type => "submit", style: 'border-style: none; background-color: #816F5B; color: #fff;' do %>
              <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          </div>
        <% end %>
      </th>
    </tr>
    <%  @orders.each do |order| %>
      <tr>
        <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order) %></td>
        <% if @customer_id == nil %>
          <td><%= order.customer.name_display %></td>
        <% end %>
        <td><%= order.total_amount.to_s(:delimited) %></td>
        <td><%= Order.statuses_i18n[order.status] %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2 class="mt-5 mb-5 ml-5">注文履歴詳細</h2>
  <div class="row">
    <table class="table table-borderless">
      <tr width="100%">
        <td width="15%"><strong>購入者</strong></td>
        <td width="85%"><%= link_to @order.customer.name_display, admin_path(customer_id: @order.customer_id) %></td>
      </tr>
      <tr>
        <td><strong>注文日</strong></td>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td><strong>配送先</strong></td>
        <td>
          <%= @order.postal_code + " " + @order.address %><br>
          <%= @order.name %>
        </td>
      </tr>
      <tr>
        <td><strong>支払方法</strong></td>
        <td><%= Order.payment_methods_i18n[@order.payment_method] %></td>
      </tr>
      <tr>
        <td><strong>注文ステータス</strong></td>
        <td>
          <div id="order_status" class="text-danger">
            <%= render "admin/orders/order_status", order: @order %>
          </div>
        </td>
      </tr>
    </table>
  </div>
  <div class="row">
    <div class="col-md-8">
      <div id="order_detail">
        <%= render "admin/orders/order_detail", order: @order %>
      </div>
    </div>
    <div class="col-md-4">
      <table class="table table-borderless">
        <tr width="100%">
          <td width="50%"><strong>商品合計</strong></td>
          <td width="50%">￥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
        </tr>
        <tr>
          <td><strong>送料</strong></td>
          <td>￥<%= @order.shipping_cost.to_s(:delimited) %></td>
        </tr>
        <tr>
          <td><strong>請求金額合計</strong></td>
          <td><strong>￥<%= @order.total_payment.to_s(:delimited) %></strong></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/update.js.erb
$("#order_status").html("<%= j(render "admin/orders/order_status", order: @order) %>");
$("#order_detail").html("<%= j(render "admin/orders/order_detail", order: @order) %>");